- name: Installing Netshow from the Cumulus Repro 
  apt: name=netshow state=present
  sudo: yes
  when: ansible_lsb.id == "Cumulus Networks"

- name: Install Netshow from Python PIP
  apt: name=python-pip state=present
  sudo: yes
  when: ansible_lsb.id == "Ubuntu"

- name: Install Netshow from Python PIP
  pip: name=netshow-linux-lib version=1.1.5
  sudo: yes
  when: ansible_lsb.id == "Ubuntu"
