- name: update loopback interfaces with vxsnd anycast address
  lineinfile: dest=/etc/network/interfaces.d/lo line="address {{ vxlan.vxsnd.anycast }}"
  sudo: yes
  
- name: ifup the loopback address
  command: "sudo ifup lo"

- name: Add loopback interface so those routes get announced
  command: "{{ item }}"
  with_items:
    - sudo cl-ospf interface set lo passive
    - sudo cl-ospf interface set lo area 0.0.0.0
    - cl-ospf network add {{ vxlan.vxsnd.anycast }}/32 area 0.0.0.0

- name: Save configuration to file
  command: sudo cl-rctl write-config

- name: configure LNV service node daemon
  template: src=daemon.j2 dest=/etc/default/vxsnd
  sudo: yes
  
- name: configure LNV service node configuration
  template: src=vxsnd.j2 dest=/etc/vxsnd.conf
  notify: restart vxsnd  
  sudo: yes
