vxlan:
  vxsnd:
    hosts:
      spine1:
      spine2:
      spine3:
    anycast: 100.254.254.254
    #routing_protocol: "osfp"
    routing_protocol: "bgp"
  vxrd:
    aa_vtep:
      leaf1: 30.1.1.12
      leaf2: 30.1.1.12
      leaf3: 30.1.1.34
      leaf4: 30.1.1.34
      leaf5: 30.1.1.56
      leaf6: 30.1.1.56
  vni:
    vni_20:
      vnid: 20
      hosts:
        leaf1: 
          vlan_id: 20
          members: "host_clag"
        leaf2: 
          vlan_id: 20
          members: "host_clag"
        leaf3:
          vlan_id: 200
          members: "host_clag"
        leaf4:
          vlan_id: 200
          members: "host_clag"
        leaf5:
          vlan_id: 20
          members: "host_clag"
        leaf6:
          vlan_id: 20
          members: "host_clag"
    vni_3000:
      vnid: 3000
      hosts:
        leaf1: 
          vlan_id: 30 
          members: "host_clag"
        leaf2: 
          vlan_id: 30
          members: "host_clag"
        leaf5:
          vlan_id: 30
          members: "host_clag"
        leaf6:
          vlan_id: 30
          members: "host_clag"
    vni_400:
      vnid: 400
      hosts:
        leaf1: 
          vlan_id: 40
          members: "host_clag"
        leaf2: 
          vlan_id: 40
          members: "host_clag"
        leaf3: 
          vlan_id: 80
          members: "host_clag"
        leaf4: 
          vlan_id: 80
          members: "host_clag"
        leaf5: 
          vlan_id: 48
          members: "host_clag"
        leaf6: 
          vlan_id: 48
          members: "host_clag"

clag:
    leaf1: "/usr/sbin/clagd --daemon 169.254.254.2 peerlink.4094 44:38:39:ff:00:02 --priority 1000 --vxlanAnycast 30.1.1.12 --vm"
    leaf2: "/usr/sbin/clagd --daemon 169.254.254.1 peerlink.4094 44:38:39:ff:00:02 --priority 1000 --vxlanAnycast 30.1.1.12 --vm"
    leaf3: "/usr/sbin/clagd --daemon 169.254.254.2 peerlink.4094 44:38:39:ff:00:03 --priority 1000 --vxlanAnycast 30.1.1.34 --vm"
    leaf4: "/usr/sbin/clagd --daemon 169.254.254.1 peerlink.4094 44:38:39:ff:00:03 --priority 1000 --vxlanAnycast 30.1.1.34 --vm"
    leaf5: "/usr/sbin/clagd --daemon 169.254.254.2 peerlink.4094 44:38:39:ff:00:04 --priority 1000 --vxlanAnycast 30.1.1.56 --vm"
    leaf6: "/usr/sbin/clagd --daemon 169.254.254.1 peerlink.4094 44:38:39:ff:00:04 --priority 1000 --vxlanAnycast 30.1.1.56 --vm"
