- name: update loopback interfaces with lnv information
  lineinfile: dest=/etc/network/interfaces.d/lo line="{{ item }}"
  with_items:
    - "vxrd-src-ip {{ ansible_lo.ipv4_secondaries.0.address }}"
    - "vxrd-svcnode-ip {{ vxlan.vxsnd.anycast }}"
  sudo: yes

- name: update loopback interfaces with active/active vtp
  lineinfile: dest=/etc/network/interfaces.d/lo line="clagd-vxlan-anycast-ip {{ vxlan.vxrd.aa_vtep[ansible_hostname] }}"
  when: vxlan.vxrd.aa_vtep[ansible_hostname] is defined
  sudo: yes

- name: turn on LNV registration node daemon
  template: src=daemon.j2 dest=/etc/default/vxrd
  sudo: yes
  notify: restart vxrd 


